### ISSUE TITLE
Add other DB?

### ISSUE THREAD

**Issue by ANTEVETY** [totaljs/dbms#1]
Convenient tool! Can couchbase be expected in future updates? Thanks

**Comment by petersirka** [comment]
__Thank you.__ Really I don't have any plan for CouchBase. I want to add MariaDB/MySQL and MongoDB. Maybe next year: Cassandra and SQLite. I used CouchDB but it wasn't enough. CouchBase is something similar with CouchDB and with implemented memcached, I think ...
