### ISSUE TITLE
DBMS for PostgreSQL doesn't catch an error

### ISSUE THREAD

**Issue by aalfiann** [totaljs/dbms#8]
Hello @petersirka ,

I just found that DBMS for PostgreSQL doesn't catch an error.

To reproduce:
```js
require('total.js');
const assert = require('assert');

function isArray (a) {
  return (!!a) && (a.constructor === Array);
}

it('database connection', async function () {
    this.timeout(120000);
    require('dbms').init('postgres://postgres:kamisama@191.168.88.25:5432/postgres', ERROR('PostgreSQL'));
    try {
      const result = await DBMS().query('select * from mydata limit 1').promise();
      if (result) {
        assert.strictEqual(isArray(result), true);
      } else {
        assert.ok(false);
      }
    } catch (err) {
      throw new Error(err);
    }
  });
```

Note:
- As you can see, the IP address is wrong, the DBMS should catch this error, but failed (has been wait for 120 second).
- If the IP address is right, but the port is wrong, DBMS successfully catch an error (connect ECONNREFUSED).
- I use totaljs 3

Please help, did I miss something?

**Comment by petersirka** [comment]
I'll look into it today. I'm adding a support for MySQL.

**Comment by petersirka** [comment]
Hi @aalfiann,
I have tested the problem, but it's not a bug. Driver tries to connect to the server, but the server doesn't respond. I think that the default timeout for Node.js Socket is 120 seconds.

The same problem with Telnet, it closes the connection after more than 120 seconds:

![image](https://user-images.githubusercontent.com/2414252/128484042-8d2aeec5-8a1c-4f88-bca4-169042e2cb77.png)

`DBMS().query()` correctly returns error in the callback, but after 120 seconds.

**Comment by aalfiann** [comment]
I never thought to test more than it, because when I try to use the wrong port, the catch is very fast. 

but I just found out that nodejs socket have a default timeout for 120 seconds.

Thank you so much @petersirka , sorry to disturb you.
